- src/main/resources/static/docs/index.html
- src/test/java/com/twogather/twogatherwebbackend/controller/LoginTest.java
- src/test/java/com/twogather/twogatherwebbackend/repository/LikesRepositoryTest.java
* docs
- 누락된 login api추가
* bug
- LikesRepositoryTest에서 오류나는 현상 수정
> twogather-web-backend-9 회원정보변경

- src/main/java/com/twogather/twogatherwebbackend/config/SecurityConfig.java
- src/main/java/com/twogather/twogatherwebbackend/controller/CommentController.java
- src/main/java/com/twogather/twogatherwebbackend/domain/Comment.java
- src/main/java/com/twogather/twogatherwebbackend/domain/Review.java
- src/main/java/com/twogather/twogatherwebbackend/dto/comment/CommentResponse.java
- src/main/java/com/twogather/twogatherwebbackend/exception/CommentException.java
- src/main/java/com/twogather/twogatherwebbackend/service/CommentService.java
- src/main/resources/application.properties
- src/main/resources/static/docs/index.html
- src/test/java/com/twogather/twogatherwebbackend/TestConstants.java
- src/test/java/com/twogather/twogatherwebbackend/TestUtil.java
- src/test/java/com/twogather/twogatherwebbackend/acceptance/AcceptanceTest.java
- src/test/java/com/twogather/twogatherwebbackend/acceptance/CommentAcceptanceTest.java
- src/test/java/com/twogather/twogatherwebbackend/controller/CommentControllerTest.java
- type: `feat`
- comment 추가, 업데이트, 삭제 api개발
- comment 관련 기능 test + controller unit test
#11
> twogather-web-backend-48 comment 개발

- src/main/java/com/twogather/twogatherwebbackend/config/SecurityConfig.java
- src/main/java/com/twogather/twogatherwebbackend/controller/EmailController.java
- src/main/java/com/twogather/twogatherwebbackend/controller/MemberController.java
- src/main/java/com/twogather/twogatherwebbackend/service/EmailService.java
- src/main/java/com/twogather/twogatherwebbackend/service/MemberService.java
- src/main/resources/static/docs/index.html
- src/test/java/com/twogather/twogatherwebbackend/acceptance/AcceptanceTest.java
- src/test/java/com/twogather/twogatherwebbackend/acceptance/MemberAcceptanceTest.java
- src/test/java/com/twogather/twogatherwebbackend/acceptance/StoreExcludeGetAcceptanceTest.java
- src/test/java/com/twogather/twogatherwebbackend/acceptance/StoreGetAcceptanceTest.java
- src/test/java/com/twogather/twogatherwebbackend/controller/MemberControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/service/StoreOwnerServiceTest.java
- type: `bug`
- 이메일 중복 확인 api 추가
- 마이페이지 정보수정에서 중복에러뜨는 현상 고치기
- #64 #11
> Twogather web backend 64

- .gitignore
- src/docs/asciidoc/index.adoc
- src/main/java/com/twogather/twogatherwebbackend/controller/ControllerAdvice.java
- src/main/java/com/twogather/twogatherwebbackend/controller/MemberController.java
- src/main/java/com/twogather/twogatherwebbackend/domain/Image.java
- src/main/java/com/twogather/twogatherwebbackend/domain/Likes.java
- src/main/java/com/twogather/twogatherwebbackend/domain/Store.java
- src/main/java/com/twogather/twogatherwebbackend/domain/StoreKeyword.java
- src/main/java/com/twogather/twogatherwebbackend/dto/store/MyLikeStoreResponse.java
- src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepository.java
- src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepositoryImpl.java
- src/main/java/com/twogather/twogatherwebbackend/service/StoreService.java
- src/main/resources/static/docs/index.html
- src/test/java/com/twogather/twogatherwebbackend/controller/MemberControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/controller/StoreControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/repository/StoreRepositoryTest.java
- type: `feat`
- 내가 좋아요 누른 가게 불러오는 api개발
- 단위테스트 수행
- api docs에 추가
- #11 #56
> Twogather web backend 66

- src/main/java/com/twogather/twogatherwebbackend/controller/ReviewController.java
- src/main/java/com/twogather/twogatherwebbackend/controller/StoreController.java
- src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepository.java
- src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepositoryImpl.java
- src/main/java/com/twogather/twogatherwebbackend/service/ReviewService.java
- src/main/java/com/twogather/twogatherwebbackend/service/StoreService.java
- src/main/resources/static/docs/index.html
- src/test/java/com/twogather/twogatherwebbackend/controller/MemberControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/controller/ReviewControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/controller/StoreControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/docs/DocumentFormatGenerator.java
- src/test/java/com/twogather/twogatherwebbackend/repository/StoreRepositoryTest.java
- src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
- type: `feat`
- storeName에 대해서도 keyword 검색 가능하게 기능 추가
- #68 #11
> Twogather web backend 68

- src/docs/asciidoc/index.adoc
- src/main/java/com/twogather/twogatherwebbackend/dto/businesshour/BusinessHourResponse.java
- src/main/resources/static/docs/index.html
- src/test/java/com/twogather/twogatherwebbackend/controller/BusinessHourControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/controller/LikeControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/controller/MemberControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/util/TestConstants.java
- src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
- type: `docs`
- docs 리팩토링
- #70
> Twogather web backend 70

- src/main/java/com/twogather/twogatherwebbackend/dto/store/StoreDefaultResponse.java
- src/main/java/com/twogather/twogatherwebbackend/dto/store/StoreResponseWithKeyword.java
- src/main/java/com/twogather/twogatherwebbackend/dto/store/TopStoreResponse.java
- src/main/java/com/twogather/twogatherwebbackend/exception/MemberException.java
- src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepositoryImpl.java
- src/main/resources/logback.xml
- src/main/resources/static/docs/index.html
- src/test/java/com/twogather/twogatherwebbackend/acceptance/AcceptanceTest.java
- src/test/java/com/twogather/twogatherwebbackend/acceptance/AdminAcceptanceTest.java
- src/test/java/com/twogather/twogatherwebbackend/acceptance/CommentAcceptanceTest.java
- src/test/java/com/twogather/twogatherwebbackend/acceptance/ImageAcceptanceTest.java
- src/test/java/com/twogather/twogatherwebbackend/acceptance/MemberAcceptanceTest.java
- src/test/java/com/twogather/twogatherwebbackend/controller/StoreControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/repository/StoreRepositoryTest.java
- src/test/java/com/twogather/twogatherwebbackend/util/TestConstants.java
- type: `feat` 
- 좋아요 개수 까지 응답으로 추가한다
- 가게 상세보기, 가게 top10, 가게 keyword검색에 추가한다
#75
> 좋아요 개수 추가하기

- src/main/java/com/twogather/twogatherwebbackend/controller/BusinessHourController.java
> security 업데이트

- src/docs/asciidoc/index.adoc
- src/main/java/com/twogather/twogatherwebbackend/service/StoreService.java
- src/main/resources/static/docs/index.html
- src/test/java/com/twogather/twogatherwebbackend/controller/AdminControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/controller/ConsumerControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/controller/StoreOwnerControllerTest.java
* feat
- isMyStore의 여부를 판가름할때 exception 대신 boolean값을 return하도록 변경
* docs
- name의 format docs에 추가
> ismystore에서 false return

- src/docs/asciidoc/index.adoc
- src/main/java/com/twogather/twogatherwebbackend/auth/JwtAuthorizationFilter.java
- src/main/java/com/twogather/twogatherwebbackend/controller/CommentController.java
- src/main/java/com/twogather/twogatherwebbackend/domain/Store.java
- src/main/java/com/twogather/twogatherwebbackend/dto/LoginResponse.java
- src/main/java/com/twogather/twogatherwebbackend/dto/comment/CommentResponse.java
- src/main/java/com/twogather/twogatherwebbackend/dto/store/StoreDefaultResponse.java
- src/main/java/com/twogather/twogatherwebbackend/exception/StoreException.java
- src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepositoryImpl.java
- src/main/java/com/twogather/twogatherwebbackend/service/CommentService.java
- src/main/resources/static/docs/index.html
- src/test/java/com/twogather/twogatherwebbackend/controller/CommentControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/controller/LoginTest.java
- src/test/java/com/twogather/twogatherwebbackend/controller/StoreControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/util/TestConstants.java
* type: `feat`
- 로그인 시 닉네임 전달
- 가게 상세보기 시 ownerid전달
- 가게 재요청 api docs에 추가
- 이미 승인된 가게 재요청 시 throw exception
> 이미 승인된 가게 재요청 시 throw exception

- src/main/java/com/twogather/twogatherwebbackend/auth/PrivateConstants.java
- src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepositoryImpl.java
* feat
- keyword사용한 가게 검색 시 페이징 size쿼리에 storeName 검색 조건 추가
> twogather-web-backend-88 기능 보충

- src/main/java/com/twogather/twogatherwebbackend/auth/AuthMessage.java
* refactoring
- 사용자 친화적 exception code 변경
> 사용자 친화적 exception code 변경

- src/main/java/com/twogather/twogatherwebbackend/TwogatherWebBackendApplication.java
- src/main/java/com/twogather/twogatherwebbackend/domain/Comment.java
- src/main/java/com/twogather/twogatherwebbackend/dto/comment/CommentResponse.java
- src/main/java/com/twogather/twogatherwebbackend/dto/review/MyReviewInfoResponse.java
- src/main/java/com/twogather/twogatherwebbackend/dto/review/StoreDetailReviewResponse.java
- src/main/java/com/twogather/twogatherwebbackend/repository/review/ReviewCustomRepositoryImpl.java
- src/main/java/com/twogather/twogatherwebbackend/service/ReviewService.java
- src/main/resources/static/docs/index.html
- src/test/java/com/twogather/twogatherwebbackend/controller/CommentControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/controller/ReviewControllerTest.java
- src/test/java/com/twogather/twogatherwebbackend/repository/ReviewRepositoryTest.java
- src/test/java/com/twogather/twogatherwebbackend/service/ReviewServiceTest.java
- src/test/java/com/twogather/twogatherwebbackend/util/TestConstants.java
> 리뷰 및 대댓글 수정사항 반영

- src/main/resources/static/docs/index.html
- src/test/java/com/twogather/twogatherwebbackend/TwogatherWebBackendApplicationTests.java
- type: `fix`
- Github Actions를 활용한 자동 배포 실패하는 현상 수정
> Github Actions를 활용한 자동 배포 실패하는 현상 수정

- src/main/resources/static/docs/index.html
- src/test/java/com/twogather/twogatherwebbackend/acceptance/AdminAcceptanceTest.java
- src/test/java/com/twogather/twogatherwebbackend/acceptance/StoreExcludeGetAcceptanceTest.java
* fix
- Github Actions를 이용한 자동 배포가 실패하는 현상 수정
> twogather-web-backend-87 리뷰 및 대댓글

- src/main/java/com/twogather/twogatherwebbackend/repository/BusinessHourRepository.java
- src/main/java/com/twogather/twogatherwebbackend/repository/ImageRepository.java
- src/main/java/com/twogather/twogatherwebbackend/repository/MemberRepository.java
- src/main/java/com/twogather/twogatherwebbackend/repository/MenuRepository.java
- src/main/java/com/twogather/twogatherwebbackend/repository/StoreKeywordRepository.java
- src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreRepository.java
- src/main/java/com/twogather/twogatherwebbackend/service/BusinessHourService.java
- src/main/java/com/twogather/twogatherwebbackend/service/ImageService.java
- src/main/java/com/twogather/twogatherwebbackend/service/MenuService.java
- src/test/java/com/twogather/twogatherwebbackend/acceptance/KeywordAcceptanceTest.java
- src/test/java/com/twogather/twogatherwebbackend/acceptance/MenuAcceptanceTest.java
- src/test/java/com/twogather/twogatherwebbackend/acceptance/StoreExcludeGetAcceptanceTest.java
* feat
- 메뉴 업데이트 제대로 되지 않는 현상 해결(repository query 제대로 작성)
> 메뉴 업데이트 쿼리 변경

- src/main/java/com/twogather/twogatherwebbackend/config/SecurityConfig.java
- src/main/java/com/twogather/twogatherwebbackend/controller/ControllerAdvice.java
- src/main/java/com/twogather/twogatherwebbackend/dto/store/MyStoreResponse.java
- src/main/java/com/twogather/twogatherwebbackend/log/CachingRequestBodyFilter.java
- src/main/java/com/twogather/twogatherwebbackend/service/CommentService.java
- src/main/resources/logback-prod.xml
* feat
- 로그에 request body추가. error발생시만 출력하도록함 (thread local사용)
- 로그에 스레드id추가
- 개인정보는 마스킹처리
- #106
> 로그에 request 정보 추가

- .gitignore
- src/main/java/com/twogather/twogatherwebbackend/controller/ControllerAdvice.java
- src/main/resources/logback-prod.xml
- src/main/resources/static/docs/index.html
* config
- 에러 로그는 별도 파일에 분리하여 출력
> 에러 로그는 별도 파일에 분리하여 출력

- src/main/resources/logback-prod.xml
> 에러 로그 콘솔에 출력

- src/test/java/com/twogather/twogatherwebbackend/util/PasswordGeneratorTest.java
> 실패하는 테스트 제외시키기
